name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/functime
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"  # Use oldest python version
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install build requires
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build setuptools
      - name: Build package
        run: python -m build --wheel
      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
